import type { ResolvedConfig } from 'vite'
import type { ManifestTransform } from 'workbox-build'
import type { VitePWAOptions } from 'vite-plugin-pwa'
import type { KitOptions } from './types'

export function configureSvelteKitOptions(
  kit: KitOptions,
  viteOptions: ResolvedConfig,
  options: Partial<VitePWAOptions>,
) {
  const {
    base = viteOptions.base ?? '/',
    adapterFallback,
    outDir = '.svelte-kit',
  } = kit

  // Vite will copy public folder to the globDirectory after pwa plugin runs:
  // globDirectory is the build folder.
  // SvelteKit will copy to the globDirectory before pwa plugin runs (via Vite client build in writeBundle hook):
  // globDirectory is the kit client output folder.
  // We need to disable includeManifestIcons: any icon in the static folder will be twice in the sw's precache manifest.
  if (typeof options.includeManifestIcons === 'undefined')
    options.includeManifestIcons = false

  let config: Partial<
    import('workbox-build').BasePartial
    & import('workbox-build').GlobPartial
    & import('workbox-build').RequiredGlobDirectoryPartial
  >

  if (options.strategies === 'injectManifest') {
    options.injectManifest = options.injectManifest ?? {}
    config = options.injectManifest
  }
  else {
    options.workbox = options.workbox ?? {}
    if (!options.workbox.navigateFallback)
      options.workbox.navigateFallback = adapterFallback ?? base

    config = options.workbox
  }

  // SvelteKit outDir is `.svelte-kit/output/client`.
  // We need to include the parent folder since SvelteKit will generate SSG in `.svelte-kit/output/prerendered` folder.
  if (!config.globDirectory)
    config.globDirectory = `${outDir}/output`

  if (!config.modifyURLPrefix)
    config.globPatterns = buildGlobPatterns(config.globPatterns)

  if (!config.manifestTransforms)
    config.manifestTransforms = [createManifestTransform(base, kit)]
}

function createManifestTransform(base: string, options?: KitOptions): ManifestTransform {
  return async (entries) => {
    const defaultAdapterFallback = 'prerendered/fallback.html'
    const suffix = options?.trailingSlash === 'always' ? '/' : ''
    let adapterFallback = options?.adapterFallback
    let excludeFallback = false
    // the fallback will be always generated by SvelteKit.
    // The adapter will copy the fallback only if it is provided in its options: we need to exclude it
    if (!adapterFallback) {
      adapterFallback = defaultAdapterFallback
      excludeFallback = true
    }

    // the fallback will be always in .svelte-kit/output/prerendered/fallback.html
    const manifest = entries.filter(({ url }) => !(excludeFallback && url === defaultAdapterFallback)).map((e) => {
      let url = e.url
      // client assets in `.svelte-kit/output/client` folder.
      // SSG pages in `.svelte-kit/output/prerendered/pages` folder.
      // fallback page in `.svelte-kit/output/prerendered` folder (fallback.html is the default).
      if (url.startsWith('client/'))
        url = url.slice(7)

      else if (url.startsWith('prerendered/pages/'))
        url = url.slice(18)

      else if (url === defaultAdapterFallback)
        url = adapterFallback!

      if (url.endsWith('.html')) {
        if (url.startsWith('/'))
          url = url.slice(1)

        if (e.url === 'index.html') {
          e.url = base
        }
        else {
          const idx = e.url.lastIndexOf('/')
          if (idx > -1) {
            // abc/index.html -> abc/?
            if (e.url.endsWith('/index.html'))
              e.url = `${e.url.slice(0, idx)}${suffix}`
            // abc/def.html -> abc/def/?
            else
              e.url = `${e.url.substring(0, e.url.lastIndexOf('.'))}${suffix}`
          }
          else {
            // xxx.html -> xxx/?
            e.url = `${e.url.substring(0, e.url.lastIndexOf('.'))}${suffix}`
          }
        }
      }
      else {
        e.url = url
      }

      return e
    })

    return { manifest }
  }
}

function buildGlobPatterns(globPatterns?: string[]): string[] {
  if (globPatterns) {
    if (!globPatterns.some(g => g.startsWith('prerendered/')))
      globPatterns.push('prerendered/**/*.html')

    if (!globPatterns.some(g => g.startsWith('client/')))
      globPatterns.push('client/**/*.{js,css,ico,png,svg,webp}')

    return globPatterns
  }

  return ['client/**/*.{js,css,ico,png,svg,webp}', 'prerendered/**/*.html']
}
